apiVersion: batch/v1
kind: Job
metadata:
  name: cassandra-schema-update
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  backoffLimit: 3
  template:
    spec:
      containers:
        - name: cqlsh
          image: cassandra:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              # Wait for Cassandra to be ready
              echo "Waiting for Cassandra to be ready..."
              sleep 30

              # Apply all CQL scripts in order
              for script in $(ls -1 /scripts/*.cql | sort); do
                echo "Applying $script..."
                cqlsh ${CASSANDRA_HOST} -u ${CASSANDRA_USERNAME} -p ${CASSANDRA_PASSWORD} -f $script
              done
          env:
            - name: CASSANDRA_HOST
              valueFrom:
                configMapKeyRef:
                  name: cassandra-config
                  key: hosts
            - name: CASSANDRA_USERNAME
              valueFrom:
                secretKeyRef:
                  name: cassandra-secrets
                  key: username
            - name: CASSANDRA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cassandra-secrets
                  key: password
          volumeMounts:
            - name: scripts
              mountPath: /scripts
      restartPolicy: Never
      volumes:
        - name: scripts
          configMap:
            name: cassandra-schema-scripts
