apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-service
  labels:
    app: post-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post-service
  template:
    metadata:
      labels:
        app: post-service
    spec:
      containers:
      - name: post-service
        image: morrishh/babbly-post-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: CassandraHosts
          value: "cassandra"
        - name: CassandraKeyspace
          value: "babbly_posts"
        - name: CassandraUsername
          value: "cassandra"
        - name: CassandraPassword
          value: "cassandra"
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka:9092"
        - name: KAFKA_POST_TOPIC
          value: "post-events" 