apiVersion: apps/v1
kind: Deployment
metadata:
  name: babbly-post-service
  labels:
    app: babbly-post-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: babbly-post-service
  template:
    metadata:
      labels:
        app: babbly-post-service
    spec:
      containers:
        - name: babbly-post-service
          image: ${DOCKER_REGISTRY}/babbly-post-service:latest
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: CassandraHosts
              valueFrom:
                configMapKeyRef:
                  name: cassandra-config
                  key: hosts
            - name: CassandraKeyspace
              valueFrom:
                configMapKeyRef:
                  name: cassandra-config
                  key: keyspace
            - name: CassandraUsername
              valueFrom:
                secretKeyRef:
                  name: cassandra-secrets
                  key: username
            - name: CassandraPassword
              valueFrom:
                secretKeyRef:
                  name: cassandra-secrets
                  key: password
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: babbly-post-service
spec:
  selector:
    app: babbly-post-service
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
